parameters:
  name: 'webdrivermanager'
  vmImage: ''

jobs:
- job: ${{ parameters.name }}
  timeoutInMinutes: 60
  cancelTimeoutInMinutes: 25
  pool:
    vmImage: ${{ parameters.vmImage }}
  strategy:
    matrix:
      Python:
        os_name:  ${{ parameters.name }}
        python_version: ${{ parameters.python_version}}
    maxParallel: 2

  steps:
  - task: UsePythonVersion@0
    displayName: 'Python for test execution'
    inputs:
      versionSpec: $(python_version)
      addToPath: true
      architecture: 'x64'

  - script: |
      python -m pip install --upgrade pip wheel
      python -m pip install -r requirements-dev.txt
    displayName: 'Install requirements'

  - script: pytest test/acceptance --junitxml acceptance_tests.xml
    displayName: 'Running Acceptance Tests'
    continueOnError: true

  - task: PublishTestResults@2
    inputs:
      testRunner: JUnit
      testResultsFiles: acceptance_tests.xml
      testResultsTitle: Acceptance Results for $(os_name) with Python $(python_version)
      testRunTitle: Python-$(python_version)-$(os_name)-acceptance
      publishRunAttachments: true

  - script: |
      flake8 --exit-zero --output flake8.xml --format=junit-xml
    displayName: 'Running Flake8 Static Analysis'
    continueOnError: true
    condition: eq(variables['os_name'], 'OSX')

  - task: PublishTestResults@2
    inputs:
      testRunner: JUnit
      testResultsFiles: flake8.xml
      testResultsTitle: Flake8 Results for $(os_name) with Python $(python_version)
      testRunTitle: Python-$(python_version)-$(os_name)-flake8
    condition: eq(variables['os_name'], 'OSX')

  - script: python setup.py sdist
    displayName: 'Generate sdist files'
